### ISSUE TITLE
:sum_all 與:list_all無法執行

### ISSUE THREAD

**Issue by matildawangh** [kkdai/LINE-Bot-ChatSummarizer#31]
感謝你的分享！我Deploy試用了之後目前:sum_all 與:list_all無法執行
想請問要如何把建立好的bot拉進現有的舊group chat（非官方帳號那種）?

謝謝! 🙏 

另外chatboat跟我說他是google的chatbot..... 
How is that possible? 😱

**Comment by matildawangh** [comment]
不好意思問題已經成功解決 🙏

**Comment by kkdai** [comment]
沒問題唷～那我關閉了 :)
